workflows:
  expo-ios-build:
    name: Expo iOS Build for TestFlight
    max_build_duration: 60
    environment:
      node: 18
      xcode: latest
      expo_token: $EXPO_TOKEN
      vars:
        APP_NAME: "Siembra"
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          npm install
      - name: Build Expo project for iOS
        script: |
          npx expo prebuild
          npx expo build:ios --non-interactive
    artifacts:
      - dist/**/*.ipa
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        api_key_id: $APPSTORE_API_KEY_ID
        issuer_id: $APPSTORE_ISSUER_ID
        key_content: $APPSTORE_P8
